### ISSUE TITLE
Home at the end of the drawing

### ISSUE THREAD

**Issue by coliss86** [coliss86/Makelangelo-software#2]

**Comment by PPAC37** [comment]
Hello !
Sorry if i over step.
For me this is to solve as in 3D printing slicer, a "start g-code" end a 'end g-code" for a printer/polargrap profil that can be customisable/modifiyed by the user.
But a quick way is juste to hard code it in the g-code generator.
Start g-code :
https://github.com/coliss86/Makelangelo-software/blob/83435e98096b91ae7a4f8cedcb3e929c503ad5bf/src/main/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java#L62
End g-code : 
https://github.com/coliss86/Makelangelo-software/blob/83435e98096b91ae7a4f8cedcb3e929c503ad5bf/src/main/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java#L96

**Comment by coliss86** [comment]
yes, this is why I have added this issue, I want to discuss it with dan before :-)
